name: Playwright Tests

on:
  push:
    branches:
      - main  # Change this if needed (e.g., develop, staging)
  pull_request:
    branches:
      - main  # Run tests on PRs too

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the same version as your local setup
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start Dev Server & Run Playwright Tests
        run: npx playwright test
