name: Playwright Tests

on:
  push:
    branches:
      - main  # Adjust this if needed
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies for Playwright
        run: npm install
        working-directory: ./playwright-pom-project  # Adjust the folder name if needed

      - name: Install dependencies for QA Homework Mirror
        run: npm install
        working-directory: ./qa-homework-mirror  # If required

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./playwright-pom-project  # Ensure correct Playwright setup

      - name: Start Dev Server & Run Playwright Tests
        run: npx playwright test
        working-directory: ./playwright-pom-project  # Ensure Playwright runs from the correct directory
